name: app_interview
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  get_it: ^7.2.0
  flutter_svg: ^1.1.3
  auto_route: ^4.2.1
  http: ^0.13.5
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.0.7
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  auto_route_generator: ^4.2.1
  json_serializable: ^6.1.5
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

